.\" This manpage 2004-2008 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "simplebackup.conf" "5" "%%%VERSION%%%" "Christian Garbs" "simple backup suite"
.SH "NAME"
.LP 
\fBsimplebackup.conf\fR \- configuration file for \fIsimplebackup\fR(1)
.SH "DESCRIPTION"
This file contains the configuration for the backups done by \fIsimplebackup\fR(1).
.SH "SYNTAX"
This file is a \fIbash\fR(1) shell script.  It is used to set some
shell variables and a shell function that are used by the backup
script.  Be careful in what you write here: the configuration file is
sourced and all commands within are executed on the beginning of a
backup.
.SH "VARIABLES"
.TP 
\fITARGETDIR\fR
This is the directory where the backup is written to.  Be sure to have
enough free disk space here.

.TP 
\fIWORKDIR\fR
This is the directory where the backup is prepared.  Disk space needed
here is the sum of all data to be backed up.  This directory will be
deleted on startup, so don't point to anyting important.

.TP 
\fIBACKUPDIRS\fR
These paths and their subdirectories are to be backed up.  Use : to
separate multiple paths.

.TP 
\fINAME\fR
This is the name of the backup.  It is later prepended with a
timestamp.

.TP 
\fILOCKFILE\fR
This lockfile is used to detect another running backup.  You can run
multiple different backups in parallel by using different lockfiles in
different configurations.

.TP 
\fINICELEVEL\fR
Nice level to run with.  20 is low priority, 0 is normal, \-20 is high
priority (only root can do this).

.TP
\fICHROOT\fR
Chroot path.  If you want to backup another system that is reachable
via your filesystem, you have to point this variable to the other
system's root directory.  Leave empty for normal operation.
.SH "FUNCTIONS"
.TP 
\fIextracommands()\fR
These commands are executed before the backup.  Here you can dump
databases, save your partition layout etc.  Put additional files to be
backed up into \fI$WORKDIR\fR or subdirectories thereof.
\fIextracommand()\fR is executed before entering a possible \fI$CHROOT\fR.

.TP 
\fIpostcopy()\fR
These commands are executed after copying all files into the
\fI$WORKDIR\fR, but before putting them into the backup archive.  If
some files need to be excluded from the \fI$BACKUPDIRS\fR then delete
them here.  \fIpostcopy()\fR is executed outside a possible \fI$CHROOT\fR.

.TP 
\fIpostbackup()\fR
These commands are executed after the backup.  The new backup filename
is available as $BACKUPFILE.
.SH "SEE ALSO"
\fIsimplebackup\fR(1),
\fIexpirebackups\fR(1)
.SH "AUTHOR"
simplebackup was written by Christian Garbs <\fImitch@cgarbs.de\fR>.
.SH "COPYRIGHT"
simplebackup is licensed under GNU GPL.
