.\" Manpage simplebackup.conf(5)
.\" Copyright (C) 2004-2009,2019,2021-2022  Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL v2 or later
.TH "simplebackup.conf" "5" "%%%VERSION%%%" "Christian Garbs" "simple backup suite"
.SH "NAME"
.LP 
.B simplebackup.conf
\- configuration file for
.BR simplebackup (1)
.SH "DESCRIPTION"
This file contains the configuration for the backups done by
.BR simplebackup (1).
.SH "SYNTAX"
This file is a
.BR bash (1)
shell script.
It is used to set some shell variables and a shell function that are used by the backup script.
Be careful in what you write here: the configuration file is sourced and all commands within are executed on the beginning of a backup.
.SH "VARIABLES"
.TP 
.I SILENT
If set to
.BR true ,
simplebackup will print only errors and warnings.
.TP 
.I DIRSTATS
If set to
.BR true ,
simeplebackup will print statistics for every directory backed up.
This needs
.BR find (1),
.BR du (1)
and
.BR wc (1).
.TP 
.I TARGETDIR
This is the directory where the backup is written to.
Be sure to have enough free disk space here.
.TP 
.I WORKDIR
This is the directory where the backup is prepared.
Disk space needed here is the sum of all data to be backed up.
This directory will be deleted on startup, so don't point to anything important.
.IP
.B Note:
The
.B $WORKDIR
set in the configuration file will be supplemented with an additional subdirectory consisting of
.B $NAME
and the current timestamp.
Be sure to use the
.B $WORKDIR
variable in your
.IR extracommands() ,
.I postcopy()
and
.I postbackup()
functions instead of hardcoding the original value.
.TP 
.I BACKUPDIRS
These paths and their subdirectories are to be backed up while crossing file system boundaries.
Use
.B :
to separate multiple paths.
.TP 
.I BACKUPDIRS_ONEFS
These paths and their subdirectories are to be backed up.
No file system boundaries will be crossed.
Use
.B :
to separate multiple paths.
.TP 
.I NAME
This is the name of the backup.
It will be supplemented by a date timestamp in format
.BR YYYYMMDD .
.TP 
.I LOCKFILE
This lockfile is used to detect another running backup.
You can run multiple different backups in parallel by using different lockfiles in different configuration files.
.TP 
.I NICELEVEL
Nice level to run with, see
.BR nice (1).
.B 19
is low priority,
.B 0
is normal,
.B -20
is high priority (this needs special capabilities, eg. root).
.TP 
.I CHROOT
Chroot path.
If you want to backup another system that is reachable via your file system, you have to point this variable to the other system's root directory.
Leave empty for normal operation.
.SH "FUNCTIONS"
.TP 
.I extracommands()
These commands are executed before the backup.
Here you can dump databases, save your partition layout etc.
Put additional files to be backed up into
.B $WORKDIR
or subdirectories thereof.
.I extracommands()
is executed before entering a possible
.BR $CHROOT .
.TP 
.I postcopy()
These commands are executed after copying all files into the
.BR $WORKDIR ,
but before putting them into the backup archive.
If some files need to be excluded from the
.B $BACKUPDIRS
then delete them here.
.I postcopy()
is executed outside a possible
.BR $CHROOT .
.TP 
.I postbackup()
These commands are executed after the backup.
The new backup filename is available in
.BR $BACKUPFILE .
.SH "SEE ALSO"
.BR simplebackup (1),
.BR expirebackups (1)
.SH "AUTHOR"
simplebackup was written by Christian Garbs
.RI < mitch@cgarbs.de >.
.SH "COPYRIGHT"
simplebackup is licensed under GNU GPL v2 or later
