--- !ditz.rubyforge.org,2008-03-06/project 
name: simplebackup
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: simplebackup
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.2
  status: :released
  release_time: 2009-01-30 19:51:21.461937 Z
  log_events: 
  - - 2009-01-30 19:46:41.908068 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2009-01-30 19:51:21.461956 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.3
  status: :released
  release_time: 2009-05-17 15:08:01.933653 Z
  log_events: 
  - - 2009-01-31 07:40:06.189876 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2009-05-17 15:08:01.933687 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.4
  status: :released
  release_time: 2009-08-13 08:43:20.984058 Z
  log_events: 
  - - 2009-05-16 16:52:36.546728 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2009-08-13 08:43:20.984092 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.5
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-08-13 08:34:47.469045 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
